#!/bin/sh
#    _____ _____ _  __ _____
#   / ___// ___/| |/_// ___/
#  / /   / /__ _>  < / /
# /_/    \___//_/|_|/_/
#        https://github.com/hgto/dots
set -xe
vim ~/.Xresources && xrdb -merge ~/.Xresources
